# Generated by Django 5.0.4 on 2024-04-25 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0006_posts_created_at_posts_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='user_post',
        ),
    ]
