# Generated by Django 5.0.4 on 2024-04-25 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0007_rename_user_posts_user_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
    ]
