# Generated by Django 5.0.4 on 2024-04-25 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0009_alter_posts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 16, 4, 19, 266273)),
        ),
    ]
